# provide a base url for github pages where repo named my_blog
baseURL = "https://t3m14.github.io/my_blog/"
languageCode = "ru-ru"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "re-terminal"
pagination.pagerSize = 5
defaultContentLanguage = 'ru'
[permalinks]
  showcase = "/showcase/"
  about = "/about/"

[params]
  author = "T3M14"
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  TocTitle = "---" # default


  # you can set a banner on the top of the page with a call to action
  # defaults: dismissible = false; URL is optional
  # [params.banner]
  # dismissible = false
  # text = "Check it out on GitHub"
  # url = "https://github.com/mirus-ua/hugo-theme-re-terminal"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.ru.params]
    languageName = "Русский"
    title = "T3M14"
    subtitle = "Личный блог, заметки и размышления. Тут я делюсь своими знаниями и опытом и вообще всем-всем, что мне кажется интересным."
    owner = "Артем Малышев"
    keywords = "блог артем малышев программирование разработка веб сайты"
    copyright = " © 2025 T3M14"
    menuMore = "Показать больше"
    readMore = "Читать далее"
    readOtherPosts = "Читать другие записи"
    newerPosts = "Новые записи"
    olderPosts = "Старые записи"
    missingContentMessage = "Страница не найдена..."
    missingBackButtonLabel = "Вернуться на главную"
    minuteReadingTime = "мин чтения"
    words = "слов"
[languages.en.params.logo]
      logoText = "T3M14"
      logoHomeLink = "/"
[[languages.ru.menu.main]]
  identifier = "about"
  name = "О сайте"
  url = "/about/"
  weight = 1

[[languages.ru.menu.main]]
  identifier = "future"
  name = "Планы на будущее"
  url = "/future/"
  weight = 2

[[languages.ru.menu.main]]
  identifier = "showcase"
  name = "Портфолио"
  url = "/showcase/"
  weight = 3

[[languages.ru.menu.main]]
  identifier = "music"
  name = "Музыкальный"
  url = "/music/"
  weight = 4